services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    container_name: mysql
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_USER", "-p$MYSQL_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/laipe/laipe/projects-manager-api:latest
    container_name: api-tasks
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  mysql_data: