### Authentification : Inscription
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "alicea",
  "password": "password123"
}

### Authentification : Connexion
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "alicea",
  "password": "password123"
}

### Créer un utilisateur
POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyMTcyNTQsImV4cCI6MTc2MDIxODE1NH0.pseZa-EyEmx2VwLMCUI3bdez9l6-eJ0IHtb2qrnQctc

{
  "username": "alicea",
  "password": "password123"
}

### Récupérer un utilisateur par ID
GET http://localhost:8080/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyMTY1NTgsImV4cCI6MTc2MDIxNzQ1OH0.S8_2bb9ngE89ufqbbcMRZHJDNzuACnn9B4QWJ8nwM1k


### Créer un projet
POST http://localhost:8080/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyMTcyNTQsImV4cCI6MTc2MDIxODE1NH0.pseZa-EyEmx2VwLMCUI3bdez9l6-eJ0IHtb2qrnQctc

{
  "name": "Projet Test",
  "creatorId": 1
}

### Récupérer un projet par ID
GET http://localhost:8080/api/projects/2

### Lister les projets d'un utilisateur
GET http://localhost:8080/api/users/1/projects

### Créer une tâche
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Tâche de test",
  "status": "TODO",
  "projectId": 1,
  "assigneeId": 1
}

### Modifier le statut d'une tâche
PATCH http://localhost:8080/api/tasks
Content-Type: application/json

{
  "id": 1,
  "status": "IN_PROGRESS"
}

### Récupérer les tâches d'un projet
GET http://localhost:8080/api/projects/1/tasks

### Récupérer les tâches d'un utilisateur
GET http://localhost:8080/api/users/1/tasks