### Créer un utilisateur
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "alicea"
}

### Récupérer un utilisateur par ID
GET http://localhost:8080/users/2


### Créer un projet
POST http://localhost:8080/projects
Content-Type: application/json

{
  "name": "Projet Test",
  "creatorId": 1
}

### Récupérer un projet par ID
GET http://localhost:8080/projects/2

### Lister les projets d'un utilisateur
GET http://localhost:8080/users/1/projects

### Créer une tâche
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Tâche 1",
  "status": "TODO",
  "projectId": 1,
  "assigneeId": 1
}

### Modifier le statut d'une tâche
PATCH http://localhost:8080/tasks
Content-Type: application/json

{
  "id": 1,
  "status": "IN_PROGRESS"
}

### Récupérer les tâches d'un projet
GET http://localhost:8080/projects/1/tasks

### Récupérer les tâches d'un utilisateur
GET http://localhost:8080/users/1/tasks 