### Authentification : Inscription
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "alicea",
  "password": "password123"
}

### Authentification : Connexion
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "alicea",
  "password": "password123"
}

### Créer un utilisateur
POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjA0OTIsImV4cCI6MTc2MDI2MTM5Mn0._XMIP_upPmKEtoEF7jpP1rd-9eJGJ0wdidNp-TZxeXs

{
  "username": "alicea",
  "password": "password123"
}

### Récupérer un utilisateur par ID
GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjA0OTIsImV4cCI6MTc2MDI2MTM5Mn0._XMIP_upPmKEtoEF7jpP1rd-9eJGJ0wdidNp-TZxeXs


### Créer un projet
POST http://localhost:8080/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjEzNzIsImV4cCI6MTc2MDI2MjI3Mn0.9UuL_ObrqTAMUKDNrR7scNt4QIPHw1eW8uWXOHVC_1U

{
  "name": "Projet Test",
  "creatorId": 1
}

### Récupérer un projet par ID
GET http://localhost:8080/api/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjEzNzIsImV4cCI6MTc2MDI2MjI3Mn0.9UuL_ObrqTAMUKDNrR7scNt4QIPHw1eW8uWXOHVC_1U

### Lister les projets d'un utilisateur
GET http://localhost:8080/api/users/1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjEzNzIsImV4cCI6MTc2MDI2MjI3Mn0.9UuL_ObrqTAMUKDNrR7scNt4QIPHw1eW8uWXOHVC_1U

### Créer une tâche
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjEzNzIsImV4cCI6MTc2MDI2MjI3Mn0.9UuL_ObrqTAMUKDNrR7scNt4QIPHw1eW8uWXOHVC_1U

{
  "title": "Tâche de test",
  "status": "TODO",
  "projectId": 1,
  "assigneeId": 1
}

### Modifier le statut d'une tâche
PATCH http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGcOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZWEiLCJpYXQiOjE3NjAyNjEzNzIsImV4cCI6MTc2MDI2MjI3Mn0.9UuL_ObrqTAMUKDNrR7scNt4QIPHw1eW8uWXOHVC_1U

{
  "id": 1,
  "status": "IN_PROGRESS"
}

### Récupérer les tâches d'un projet
GET http://localhost:8080/api/projects/1/tasks

### Récupérer les tâches d'un utilisateur
GET http://localhost:8080/api/users/1/tasks