name: CI/CD — Build / Test / Push / Deploy
on:
  push:
    branches: [ main ]


permissions:
  contents: read
  packages: write    # pour GHCR

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Setup Java 21 ----------
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # ---------- Run tests ----------
      - name: Run tests
        run: mvn test

      # ---------- Set lowercase variables ----------
      - name: Set lowercase variables
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.repository }}'

      # ---------- Login to GHCR registry ----------
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- Build and push image ----------
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Setup SSH key for deploy ----------
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # ---------- Copy docker-compose.prod.yml to VPS ----------
      - name: Copy docker-compose.prod.yml to VPS
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_HOST: ${{ secrets.VPS_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.prod.yml ${SSH_USER}@${SSH_HOST}:${{ secrets.VPS_APP_PATH }}/docker-compose.prod.yml

      # ---------- Deploy: SSH to VPS and run docker-compose ----------
      - name: Deploy to VPS
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} '
            cd ${{ secrets.VPS_APP_PATH }} || exit 1
            docker compose -f docker-compose.prod.yml --env-file .env.prod pull
            docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --remove-orphans
          '
